### ISSUE TITLE
Ready for production?

### ISSUE THREAD

**Issue by royandre** [emartech/magento2-extension#6]
Not strictly an Issue, but what is the current status of this module? Is it ready for production usage? Are there any known clients using the module?

Do you guys allow for receiving PRs for it?

**Comment by dszucs-emarsys** [comment]
The module is in piloting phase, currently used on two dev sites as well as two other clients being onboarded for production use.

Any PRs are welcome.

**Comment by r8r** [comment]
@dszucs-emarsys we are in the process of finishing a Magento 1.9 to 2.3 migration next week. Right now we are debating whether we have to remove the emarsys components due to lack of support. Neither 1st level support, nor "Success Management" has been able to provide any helpful information to us on a roadmap so far.
Can you possibly shed some light on this? Thank you!

**Comment by BlasiusVonSzerencsi** [comment]
Hi @r8r ,

The extension is in the piloting phase. There are known limitations, most of which will be addressed in the next quarter.
The Magento 2.3 compilation issue is one of the most urgent problems, it will be fixed in the near future.

Any issue and/or feature request is welcome. We'll most definitely try to understand the client use-cases and come up with a fitting solution.

Thanks,
Balazs

**Comment by r8r** [comment]
Thanks @BlasiusVonSzerencsi ,
if I understand you correctly, an RC is expected be ready sometime in Q2?

Our most crucial need to get the project out of the door and launched, really is just getting email addresses of newly signed up clients into your system, segmented by language (currently only two).
I assume these are very basic cases and I was wondering, whether using this extension in prod would hit any of the aforementioned limitations? Additional features are planned, so we'd rather start out by using official code instead of building something ourselves and then replacing it with a successor of this current codebase after all.

Thanks!
Mario

**Comment by iben12** [comment]
Hi @r8r,
Sorry for replying a bit late, but with the v1.4.0 release Magento 2.3 support was added to the extension. You're welcome to test drive it.

**Comment by r8r** [comment]
Thank you @iben12 

we were in touch with one of your Solution Consultants by phone last week and actually are in the process of trying to implement is, as I am typing.
